### ISSUE TITLE
Uncaught TypeError: Duration::fromNanoseconds() must be of the type int, float given

### ISSUE THREAD

**Issue by CreativeNative** [sebastianbergmann/php-timer#31]
PHPUnit 9.2.1
PHPTimer 4.0.0
Runtime: PHP 7.4.6 with Xdebug 2.9.5

After updating to PHPUnit 9.2.1 with PHPTimer 4.0.0 I got this error.

In version PHPUnit 9.1.5 with PHPTimer 3.1.4 this error doesn't occure. 

PHPUnit\Framework\Exception: PHP Fatal error:  **Uncaught TypeError: Argument 1 passed to SebastianBergmann\Timer\Duration::fromNanoseconds() must be of the type int, float given**, called in /vendor/phpunit/php-timer/src/Timer.php on line 35 and defined in /vendor/phpunit/php-timer/src/Duration.php:47
   │ Stack trace:
   │ #0 /vendor/phpunit/php-timer/src/Timer.php(35): SebastianBergmann\Timer\Duration::fromNanoseconds()
   │ #1 /vendor/phpunit/phpunit/src/Framework/TestResult.php(743): SebastianBergmann\Timer\Timer->stop()
   │ #2 /vendor/phpunit/phpunit/src/Framework/TestCase.php(771): PHPUnit\Framework\TestResult->run()
   │ #3 Standard input code(392): PHPUnit\Framework\TestCase->run()
   │ #4 Standard input code(584): __phpunit_run_isolated_test()
   │ #5 {main}
   │   thrown in /vendor/phpunit/php-timer/src/Duration.php on line 47
   │
   │ Fatal error: Uncaught TypeError: Argument 1 passed to SebastianBergmann\Timer\Duration::fromNanoseconds() must be of the type int, float given, called in /vendor/phpunit/php-timer/src/Timer.php on line 35 and defined in /vendor/phpunit/php-timer/src/Duration.php on line 47
   │
   │ TypeError: Argument 1 passed to SebastianBergmann\Timer\Duration::fromNanoseconds() must be of the type int, float given, called in /vendor/phpunit/php-timer/src/Timer.php on line 35 in /vendor/phpunit/php-timer/src/Duration.php on line 47
   │
   │ Call Stack:
   │     0.0019     511792   1. {main}() Standard input code:0
   │     0.2221    4949016   2. __phpunit_run_isolated_test() Standard input code:584
   │     0.2251    5035944   3. ApplicationTest\ModuleTest->run() Standard input code:392
   │     0.2252    5035944   4. PHPUnit\Framework\TestResult->run() /vendor/phpunit/phpunit/src/Framework/TestCase.php:771
   │     0.3580    6261320   5. SebastianBergmann\Timer\Timer->stop() /vendor/phpunit/phpunit/src/Framework/TestResult.php:743
   │     0.3592    6270248   6. SebastianBergmann\Timer\Duration::fromNanoseconds() /vendor/phpunit/php-timer/src/Timer.php:35

**Comment by sebastianbergmann** [comment]
Are you on a 32bit system?

**Comment by sebastianbergmann** [comment]
`hrtime()` returns `float` instead of `int` on 32-bit systems. I am sorry, but I did not expect 32-bit systems to still be used.
